### ISSUE TITLE
Skwissh doesn't works with Django 1.5

### ISSUE THREAD

**Issue by morsik** [rsaikali/django-skwissh#18]
It uses deprecated functions since Django 1.3, and they are now removed in Django 1.5.

  File "/home/morsik/venv/skwissh/lib/python2.7/site-packages/skwissh/urls.py", line 6, in <module>
    from django.views.generic import list_detail
ImportError: cannot import name list_detail

and:

  File "/home/morsik/venv/skwissh/lib/python2.7/site-packages/django/core/urlresolvers.py", line 104, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import django.views.generic.simple.direct_to_template. Parent module django.views.generic.simple does not exist.
